# Generated by Django 3.2 on 2021-06-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210601_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='actor',
            name='city',
            field=models.CharField(default='London', max_length=20),
            preserve_default=False,
        ),
    ]
